CREATE TABLE Card (
SetID	 VARCHAR(10) 	NOT NULL,
CardType VARCHAR(9),
CardName VARCHAR(30),
PRIMARY KEY (SetID)
); 

CREATE TABLE UserD ( 
UserID	SMALLINT	NOT NULL, 
Email	VARCHAR(40)	NOT NULL, 
DoB	DATE, 
PRIMARY KEY(UserID, Email)
);

CREATE TABLE CardSet (
SetName  VARCHAR(30)	NOT NULL,
SetDate	 DATE,
NumCards SMALLINT,
PRIMARY KEY(SetName)
);

CREATE TABLE Deck (
DeckName  VARCHAR(25)	NOT NULL,
UserID	  INT(10)		NOT NULL,
PRIMARY KEY(DeckName, UserID),
FOREIGN KEY(UserID) REFERENCES UserD(UserID)
	ON DELETE CASCADE
);

CREATE TABLE Includes ( 
SetID	 VARCHAR(10)	NOT NULL, 
DeckName VARCHAR(25) 	NOT NULL,
Copies 	 SMALLINT(1),
PRIMARY KEY(SetID, DeckName),
FOREIGN KEY(SetID) REFERENCES Card(SetID)
	ON DELETE CASCADE,
FOREIGN Key(DeckName) REFERENCES Deck(DeckName)
	ON DELETE CASCADE
); 

CREATE TABLE Contain (
SetID	 VARCHAR(10)	NOT NULL,
SetName  VARCHAR(30) 	NOT NULL,
PRIMARY KEY(SetID, SetName),
FOREIGN KEY(SetID) REFERENCES Card(SetID)
	ON DELETE CASCADE,
FOREIGN KEY(SetName) REFERENCES CardSet(SetName)
);

CREATE TABLE Owns (
SetID	 VARCHAR(10)	NOT NULL,
UserID	 INT(10)		NOT NULL,
Quantity SMALLINT(1),
PRIMARY KEY(SetID, UserID),
FOREIGN KEY(SetID) REFERENCES Card(SetID)
	ON DELETE CASCADE,
FOREIGN KEY(UserID) REFERENCES UserD(UserID)
	ON DELETE CASCADE
); 

